hyperledger/quilt

ilp-core-codecs/README.md, ilp-core-codecs/src/test/java/org/interledger/core/asn/codecs/InterledgerPreparePacketOerSerializerTests.java, ilp-core/src/main/java/org/interledger/core/InterledgerFulfillPacket.java, ilp-core/src/main/java/org/interledger/core/InterledgerPreparePacket.java, ilp-core/src/main/java/org/interledger/core/InterledgerRejectPacket.java, ilp-core/src/test/java/org/interledger/core/InterledgerPreparePacketTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerRejectPacketTest.java
* Eases the ILP v4 packets impl usage by initializing their 'data' field to empty.
Signed-off-by: Pascal Avondes <pavondes@gmail.com>
=> Fixes #119

btp-core/src/main/java/org/interledger/btp/BtpSubProtocolContentType.java, btp-core/src/test/java/org/interledger/btp/BtpSubProtocolContentTypeTest.java, ilp-core-codecs/src/main/java/org/interledger/core/asn/codecs/AsnInterledgerAddressPrefixCodec.java, ilp-core-codecs/src/main/java/org/interledger/core/asn/framework/InterledgerCodecContextFactory.java, ilp-core-codecs/src/test/java/org/interledger/core/asn/codecs/AsnInterledgerAddressCodecTest.java, ilp-core-codecs/src/test/java/org/interledger/core/asn/codecs/AsnInterledgerAddressPrefixCodecTest.java, ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java, ilp-core/src/main/java/org/interledger/core/InterledgerAddressPrefix.java, ilp-core/src/main/java/org/interledger/core/InterledgerPacket.java, ilp-core/src/main/java/org/interledger/core/InterledgerPreparePacket.java, ilp-core/src/main/java/org/interledger/core/InterledgerProtocolException.java, ilp-core/src/main/java/org/interledger/core/InterledgerRejectPacket.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressPrefixTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerPreparePacketTest.java
* Revert InterledgerAddress.value to `getValue`.
* Add `InterledgerAddressPrefix` that can be an address or allocation scheme, plus unit test.
* Add Codec for `InterledgerAddressPrefix`, plus unit tests.
* Move `data` to `InterlederPacket` parent interface.
* Set default value of Prepare packet to ZERO.
* Add Javadoc to InterledgerFulfillPacket.
* Make BtpSubProtocolContentTypeTest use the proper type (Short).
=> Misc Packet Cleanup

jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerModule.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/address/InterledgerAddressModule.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/conditions/ConditionModule.java
- Avoids hard coding of strings for canonical names and simple names.
=> Replaces fixed identifier to CanonicalNames and SimpleNames for corresponding classes

ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
- Add `startsWith()` to accept `InterledgerAddressPrefix`
- Add corresponding tests for `InterledgerAddress` that `startsWith(prefix)`
=> Fixes #199 Adds startsWith(prefix) and tests to the InterledgerAddress interface

ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
- Implements `with()` to create `InterledgerAddress` using `AllocationScheme`
- Writes corresponding tests for valid and invalid usages of `with()`
- Tests the integrity of the created `InterledgerAddress` objects with those from `of()`
=> Fixes #197 Implements with to create Address using AllocationScheme

ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
- The `SEGMENTS_UNDERFLOW` logic ensures that `InterledgerAddress` always contains a prefix.
- Removes optionality from the `getPrefix()` method and updates `hasPrefix()` accordingly.
- Updates corresponding tests and implements explicit checking of `hasPrefix()` and `getValue()` checks.
- Removes `hasPrefix()` since the`InterledgerAddress` always has a prefix.
=> Fixes #212 Remove Optionality from InterledgerAddress getPrefix

ilp-core/src/main/java/org/interledger/core/InterledgerAddressPrefix.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressPrefixTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
- Removes `SEGMENTS_UNDERFLOW` check for `InterledgerAddressPrefix` as this cannot be reached.
- Adds explicit test cases for `InterledgerAddress#of` and `InterledgerAddressPrefix#of`.
- Update error message if a corner case slips through the checks and ask users to report a bug.
=> Fixes #214 Adds Overt test cases for of() and removes SEGMENTS_UNDERFLOW in Prefix

stream-parent/stream-core/src/main/java/org/interledger/stream/StreamUtils.java, stream-parent/stream-core/src/main/java/org/interledger/stream/crypto/JavaxStreamEncryptionService.java
=> Using StandardCharsets instead of Charset.forName for US-ASCII

stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java, stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java, stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SimpleStreamSenderTests.java, stream-parent/stream-core/src/main/java/org/interledger/stream/StreamPacket.java, stream-parent/stream-core/src/main/java/org/interledger/stream/StreamUtils.java, stream-parent/stream-core/src/test/java/org/interledger/stream/StreamPacketTest.java, stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StatelessStreamReceiver.java, stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/StatelessStreamReceiverTest.java
* Per IL-RFC-29, ensure that the number of StreamPackets does not exceed 2^31.
* Add unit test coverage to STREAM sender and receiver.
* Enhance StreamPacket to allow easily computing this condition.
=> Fixes #236 (Max Sequence Number)

examples/send-money/pom.xml, examples/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java, stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java, stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java, stream-parent/stream-core/src/main/java/org/interledger/stream/SendMoneyResult.java, stream-parent/stream-core/src/test/java/org/interledger/stream/SendMoneyResultTest.java
track how much money was sent from the sender's perspective instead of receiver's
fix issue with ScheduledThreadPoolExecutor not getting shutdown
Signed-off-by: nhartner <nhartner@gmail.com>
=> fix bug with sendMoney between accounts in different assets

stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java, stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/SenderReceiverTest.java
add multithreaded tests to SenderReceiverTest
add tests for right-to-left and left-to-right sends
fix live lock issue with SimpleStreamSender
addresses https://github.com/hyperledger/quilt/issues/273
=> Add multithreaded tests to SenderReceiverTest

.circleci/config.yml, ilp-core/pom.xml, link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/auth/JwtHs256BearerTokenSupplier.java, link-parent/link-ilp-over-http/src/test/java/org/interledger/link/http/auth/JwtHs256BearerTokenSupplierTest.java, pom.xml
* Use android-compatible API for token expiry.
* Update build file to easily support building for both JRE and Android platforms.
=> Fixes #341 (Make Quilt work on Android)

README.md
Moving to LGTM because it provides security audit coverage and it's unclear if codacy does that.
=> Fix LGTM Badge

ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java, ilp-core/src/main/java/org/interledger/core/InterledgerAddressPrefix.java, ilp-core/src/test/java/org/interledger/core/AllocationSchemeTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressPrefixTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java, ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java, jackson-datatypes/pom.xml, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdDeserializer.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdModule.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdSerializer.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeDeserializer.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeModule.java, jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeSerializer.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdContainer.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdDeserializerTest.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdSerializerTest.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkModuleTest.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeContainer.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeIdDeserializerTest.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeModuleTest.java, jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeSerializerTest.java
* Fixes #362 to account for the `local` AllocationScheme.
* Adds Jackson support for `LinkId` and `LinkType`
* Improve unit test coverage.
=> Add link Jackson serializers and Fix #362

README.md
The following commit hashes are missing their DCO sign-off, but I attest these commits were made by me.
* 33082e4cc2ded3fafbfb26fb42d804bfd8e7edd7
* 2703db00ad5d43cfed66cdf35e0d77c6b110a9fc
=> DCO Attestation for prior commits

examples-parent/send-money/README.md, examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java, spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/SimpleSpspClient.java, spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/SpspClient.java, spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/SpspClientDefaults.java, spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/rust/InterledgerRustNodeClient.java, spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/rust/RustNodeAccount.java, spsp-parent/spsp-client/src/test/java/org/interledger/spsp/client/SimpleSpspClientTest.java, spsp-parent/spsp-client/src/test/java/org/interledger/spsp/client/rust/InterledgerRustNodeClientTest.java, stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SimpleStreamSenderIT.java
Add SPSP client method that takes resolved URL instead of payment pointer. Fixes #381
Create a generic implementation of SPSP client. Fixes #380 
update README with correct. Fixes #379
=> Refactor SPSP client to its own client not coupled to Rust client

stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SimpleStreamSenderIT.java
long live interledgerrs/ilp-node
fixes #384
=> stop using deprecated interledgerrs/node docker image

.circleci/config.yml
=> compute JDK14 url dynamically since it changes every time openjdk publishes a new early-access version

stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/SpspStreamConnectionGenerator.java, stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/SpspStreamStreamConnectionGeneratorTest.java
* Align the SPSP connection generator with the JS and Rust implementations.
* Allow local parts that are longer than 32 bytes.
* Allow a configurable `streamServerSecretGenerator`.
=> Make STREAM_SERVER_SECRET_GENERATOR configurable (Fixes #374)

stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java, stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java, stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SleepyExecutorService.java
fixes a bug where the expiresAt could already be expired since it was being computed before calling executorService.submit() and the executorService is queueing up tasks (due to being backed up)
address #432
=> compute a packet's expiresAt just before sending on the link

spsp-parent/spsp-core/src/main/java/org/interledger/spsp/PaymentPointer.java, spsp-parent/spsp-core/src/test/java/org/interledger/spsp/PaymentPointerTest.java
I'd like to make WELL_KNOWN a public constant. This is useful because it means that there is a source of truth for this value. 
In practice, this improves our test code because we no longer have to hard code this magic constant.
=> Make `WELL_KNOWN` constant public

codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/serializers/oer/AsnOctetStringOerSerializer.java, codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/serializers/oer/AsnOpenTypeOerSerializer.java, codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/serializers/oer/OerLengthSerializer.java, codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/OerLengthSerializerTest.java, codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/OerLengthSerializerTestBadLength.java, codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/OerLengthSerializerToIntTest.java
Clarify the construction of an ASN.1 OER length-prefix. Also add better unit tests.
NOTE: This PR requires https://github.com/hyperledger/quilt/pull/446 to merge first.
=> Clarify length prefix contract

codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/StreamPacketFixturesTest.java, examples-parent/send-money/pom.xml, examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java, examples-parent/send-money/src/main/resources/logback.xml, pom.xml
* Add plugin to create executable jar
* Fix debug logging in example.
=> Update SendMoney for new Server

codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnConnectionNewAddressFrameDataCodec.java, codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/StreamPacketFixturesTest.java, codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/AsnConnectionNewAddressFrameCodecTest.java, pom.xml, stream-parent/stream-core/src/main/java/org/interledger/stream/frames/ConnectionNewAddressFrame.java, stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamFrameTypeTest.java
This change enables backwards compatibility with the JS Interledger implementations and overall supports more Stream use-cases in a backwards compatible manner.
For more details, see https://github.com/interledger/rfcs/pull/573
=> Make ConnectionNewAddress Frame's address optional address

codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnSequenceCodec.java, codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnSequenceOfSequenceCodec.java, codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/StreamPacketFixturesTest.java
If a particular frame in a StreamPacket cannot be decoded for whatever reason, we should not swallow exception. See comments in unit test code for rationale.
Fixes #455
=> Validate failure on invalid STREAM frames

examples-parent/ilp-emitters/src/main/java/org/interledger/examples/packets/IlpPacketEmitter.java, ildcp-core/src/main/java/org/interledger/ildcp/IldcpRequestPacket.java, ildcp-core/src/main/java/org/interledger/ildcp/IldcpResponsePacket.java, ilp-core/src/main/java/org/interledger/core/InterledgerPacket.java, stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java, stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StatelessStreamReceiver.java, stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/StatelessStreamReceiverTest.java
Allows any InterledgerPacket to contain a typed variant of the packet's `data` payload. This is specifically added to optimize STREAM packet handling so that different parts of the Connector or ILP node runtime do not need to re-decrypt STREAM information if a packet is operated upon at various parts of the PacketSwitch.
The field is optional so it can be added in a backwards-compatible manner (and also this contract makes the most sense because typedData may not exist in all use-cases).
=> Add typeData field to InterledgerPacket
