hyperledger/quilt

- README.md
* hyperlink to ilp-core and dev-ops
* It's its, not it's
* Remove trailing whitespace
> docs: ilp-core hyperlink and nits in readme

- .circleci/config.yml
- .gitignore
- pom.xml
Moved plugin config to pluginManagement
Added .gitignore
Signed-off-by: adrianhopebailie <adrian@hopebailie.com>
> Fix Jacoco tests

- .gitignore
- crypto-conditions/pom.xml
- dev-ops/src/main/resources/org/interledger/dev-ops/checkstyle.xml
- ilp-core/pom.xml
- ilp-core/src/main/java/org/interledger/InterledgerAddress.java
- ilp-core/src/main/java/org/interledger/codecs/CodecContext.java
- ilp-core/src/main/java/org/interledger/ilp/InterledgerPayment.java
- ilp-core/src/main/java/org/interledger/psk/PskEncryptionHeader.java
- ilp-core/src/main/java/org/interledger/psk/PskNonceHeader.java
- ilp-core/src/test/java/org/interledger/InterledgerAddressBuilderTest.java
- ilp-core/src/test/java/org/interledger/InterledgerAddressSchemeTest.java
- ilp-core/src/test/java/org/interledger/InterledgerAddressTest.java
- pom.xml
* Fixes #45.
* Fixes #46.
* Fixes #47.
* Fixes checkstyle configuration, and actually runs checkstyle during the build.
> Fixes #45, Fixes #46, Fixes #47

- crypto-conditions/src/main/java/org/interledger/cryptoconditions/CryptoConditionWriter.java
- crypto-conditions/src/main/java/org/interledger/cryptoconditions/Ed25519Sha256Fulfillment.java
- crypto-conditions/src/main/java/org/interledger/cryptoconditions/Fulfillment.java
- crypto-conditions/src/main/java/org/interledger/cryptoconditions/PrefixSha256Fulfillment.java
- crypto-conditions/src/main/java/org/interledger/cryptoconditions/PreimageSha256Fulfillment.java
- crypto-conditions/src/main/java/org/interledger/cryptoconditions/RsaSha256Fulfillment.java
- crypto-conditions/src/main/java/org/interledger/cryptoconditions/ThresholdSha256Fulfillment.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/CryptoConditionReaderWriterTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/Ed25519Sha256FulfillmentTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/PrefixSha256FulfillmentTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/PreimageSha256ConditionTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/PreimageSha256FulfillmentTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/RsaSha256FulfillmentTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/ThresholdSha256ConditionTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/ThresholdSha256FulfillmentTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/ValidVectorTest.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/helpers/TestConditionFactory.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/helpers/TestVectorFactory.java
- jackson-datatypes/jackson-datatype-cryptoconditions/src/test/java/org/interledger/quilt/jackson/cryptoconditions/AbstractCryptoConditionsModuleTest.java
- jackson-datatypes/jackson-datatype-interledger/src/test/java/org/interledger/quilt/jackson/InterledgerModuleTest.java
> Rename Fulfillment.getCondition to Fulfillment.getDerivedCondition

- crypto-conditions/src/main/java/org/interledger/cryptoconditions/ThresholdSha256Condition.java
- crypto-conditions/src/test/java/org/interledger/cryptoconditions/ThresholdSha256ConditionTest.java
...to accept an Immutable list
Addresses #67
> Fix ThresholdSha256Condition#calculateCost

- ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java
- ilp-core/src/main/java/org/interledger/core/InterledgerAddressParser.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressBuilderTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressParserTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
* Enhances the ILP address error check into a parser class
Signed-off-by: Pascal Avondes <pavondes@gmail.com>
> Fixes #104

- README.md
> Fix README for JCE encryption requirements

- ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java
> Javadoc Cleanup

- codec-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUintCodec.java
- codec-framework/src/test/java/org/interledger/encoding/MyCustomObject.java
- codec-framework/src/test/java/org/interledger/encoding/asn/AsnMyCustomObjectCodec.java
- codec-framework/src/test/java/org/interledger/encoding/asn/framework/EncodingTests.java
Signed-off-by: adrianhopebailie <adrian@hopebailie.com>
> Fixes #133

- pom.xml
Signed-off-by: Kai Chu <chuck.chu.liu@gmail.com>
> Fixes #147 : Changed hard code module groupId and version dependency

- btp-core-codecs/src/main/java/org/interledger/btp/asn/codecs/AsnBtpTransferDataCodec.java
Allow BtpTransfer to be constructed.
> Fixes #151

- btp-core/src/main/java/org/interledger/btp/BtpSubProtocol.java
> Add intelligent defaults to BtpSubProtocol

- ilp-core-codecs/src/main/java/org/interledger/core/asn/codecs/AsnInterledgerAddressCodec.java
- ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/address/InterledgerAddressSerializer.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/InterledgerModuleTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/address/InterledgerAddressModuleTest.java
Change `InterlederAddress#value` to `InterledgerAddress#getValue` per [the discussion in this PR](https://github.com/hyperledger/quilt/pull/165#discussion_r207726244).
> Fixes #168

- pom.xml
* Change `<id>` to `<serverId`>
* Update immutables version to 2.7.1
* Update maven-gpg-plugin to 1.6
> Fixes #176

- pom.xml
* See https://discuss.circleci.com/t/circleci-build-failure-on-openjdk-image/26104/2
> Fix broken build in CircleCI

- ilp-core/src/main/java/org/interledger/core/InterledgerRejectPacket.java
> fix java doc as mention in spec

- ilp-core-codecs/src/test/java/org/interledger/core/asn/codecs/InterledgerRejectPacketOerSerializerTests.java
- ilp-core/src/main/java/org/interledger/core/InterledgerErrorCode.java
- ilp-core/src/test/java/org/interledger/core/InterledgerErrorCodeTest.java
> Fixes #185

- pom.xml
> Update Checkstyle version

- ildcp-core/src/main/java/org/interledger/ildcp/IldcpResponsePacket.java
- ildcp-core/src/test/java/org/interledger/ildcp/IldcpResponsePacketTest.java
- ilp-core/src/main/java/org/interledger/core/package-info.java
- jackson-datatypes/pom.xml
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/conditions/AbstractConditionModuleTest.java
- pom.xml
* Update Jackson for securit alert
* Fix unit tests
* Remove unused bcprov libraries.
> Update dependency versions

- btp-core-codecs/src/main/java/org/interledger/btp/asn/framework/BtpCodecContextFactory.java
- codec-framework/src/main/java/org/interledger/encoding/asn/framework/CodecContext.java
- codec-framework/src/main/java/org/interledger/encoding/asn/framework/CodecContextFactory.java
- codec-framework/src/test/java/org/interledger/encoding/asn/framework/EncodingTests.java
- codec-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/AbstractSerializerTest.java
- codec-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/ByteArrayOerSerializerTest.java
- codec-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/IA5StringOerSerializerTestBadLength.java
- codec-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/OpenTypeOerSerializerTest.java
- codec-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/SequenceOfSequenceIntOerSerializerTest.java
- codec-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/SequenceOfSequenceShortOerSerializerTest.java
- ildcp-core-codecs/src/main/java/org/interledger/ildcp/asn/framework/IldcpCodecContextFactory.java
- ildcp-core-codecs/src/test/java/org/interledger/ildcp/asn/framework/IldcpCodecContextFactoryTest.java
- ilp-core-codecs/src/main/java/org/interledger/core/asn/framework/InterledgerCodecContextFactory.java
> Fixes #200 Aligns codec registration methods to use register from oer

- README.md
- btp-core-codecs/pom.xml
- btp-core/pom.xml
- codec-framework/pom.xml
- dev-ops/pom.xml
- ildcp-core-codecs/pom.xml
- ildcp-core/pom.xml
- ilp-core-codecs/pom.xml
- ilp-core/pom.xml
- jackson-datatypes/README.md
- jackson-datatypes/pom.xml
- pom.xml
> Update for new version

- btp-core-codecs/src/main/java/org/interledger/btp/asn/codecs/AsnBtpErrorDataCodec.java
- btp-core-codecs/src/main/java/org/interledger/btp/asn/framework/BtpCodecContextFactory.java
- btp-core-codecs/src/test/java/org/interledger/btp/asn/codecs/AsnBtpInstantSerializationTest.java
- btp-core/src/main/java/org/interledger/btp/BtpErrorCode.java
- btp-core/src/main/java/org/interledger/btp/BtpSubProtocols.java
- codec-framework/src/main/java/org/interledger/encoding/asn/serializers/oer/OerLengthSerializer.java
- ildcp-core-codecs/src/main/java/org/interledger/ildcp/IldcpUtils.java
- ildcp-core/src/main/java/org/interledger/ildcp/IldcpResponsePacket.java
- ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java
- jackson-datatypes/README.md
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerDeserializers.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerModule.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerSerializers.java
> Fixes #219 Addresses typos throughout the project

- ilp-core/src/main/java/org/interledger/core/InterledgerAddressPrefix.java
> Fixes #219 Updates documentation errors in InterledgerAddressPrefix

- ilp-core/src/main/java/org/interledger/core/InterledgerPacketType.java
- ilp-core/src/test/java/org/interledger/core/InterledgerPacketTypeTest.java
> Fixes #245 Implements unit tests for InterledgerPacketType

- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/AimdCongestionControllerTest.java
I also converted from hamcrest to assertj.
> add unit tests for f08 packet; fixes #266

- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SimpleStreamSenderIT.java
Signed-off-by: nhartner <nhartner@gmail.com>
> lookup docker container ip address rather than assume it's localhost

- checkstyle.xml
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressPrefixTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerConditionTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerConstantsTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerErrorCodeTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerFulfillmentTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerPacketTypeTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerRejectPacketTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerResponsePacketTest.java
- ilp-core/src/test/java/org/interledger/core/WrapperTest.java
- Initial follow up on #243 after introducing #298 
> Cleans up tests corresponding to ilp core and adds @SuppressWarning annotations

- README.md
- examples/README.md
- examples/pom.xml
- examples/send-money/README.md
- examples/send-money/pom.xml
- examples/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java
- pom.xml
- spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/rust/InterledgerRustNodeClient.java
Signed-off-by: nhartner <nhartner@gmail.com>
> examples module with a sub-module for showing how to send money over ILP with Quilt

- btp-core/src/main/java/org/interledger/btp/BtpError.java
- btp-core/src/test/java/org/interledger/btp/BtpErrorTest.java
> Fixes #313 Addresses toString serialization bug and corresponding tests for `btp-core`

- stream-parent/stream-core/src/main/java/org/interledger/stream/StreamConnection.java
- stream-parent/stream-core/src/test/java/org/interledger/stream/StreamConnectionTest.java
> Fixes #310 Implements Closeable in StreamConnection

- stream-parent/stream-client/src/main/java/org/interledger/stream/sender/FixedReceiverAmountPaymentTracker.java
- stream-parent/stream-client/src/main/java/org/interledger/stream/sender/FixedSenderAmountPaymentTracker.java
- stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java
- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/FixedSenderAmountPaymentTrackerTest.java
- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
- stream-parent/stream-core/src/main/java/org/interledger/stream/PaymentTracker.java
> Preconditions to prevent over sending

- README.md
Update description of various modules.
> Update README.md for v1.0 release

- btp-core/pom.xml
- codecs-parent/codecs-btp/pom.xml
- codecs-parent/codecs-framework/pom.xml
- codecs-parent/codecs-ildcp/pom.xml
- codecs-parent/codecs-ilp/pom.xml
- codecs-parent/codecs-stream/pom.xml
- codecs-parent/pom.xml
- examples-parent/pom.xml
- examples-parent/send-money/pom.xml
- ildcp-core/pom.xml
- ilp-core/pom.xml
- jackson-datatypes/pom.xml
- link-parent/link-core/pom.xml
- link-parent/link-ilp-over-http/pom.xml
- link-parent/pom.xml
- pom.xml
- spsp-parent/pom.xml
- spsp-parent/spsp-client/pom.xml
- spsp-parent/spsp-core/pom.xml
- stream-parent/pom.xml
- stream-parent/stream-client/pom.xml
- stream-parent/stream-core/pom.xml
- stream-parent/stream-receiver/pom.xml
Signed-off-by: nhartner <nhartner@gmail.com>
> change version to HEAD-SNAPSHOT

- stream-parent/stream-client/src/main/java/org/interledger/stream/sender/FixedSenderAmountPaymentTracker.java
- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/FixedSenderAmountPaymentTrackerTest.java
- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
> check to make sure we don't send too much

- ilp-core/pom.xml
- pom.xml
> fix poms for releases

- .circleci/config.yml
- pom.xml
- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
> Fixes #345 Builds the project on available JDK images in CircleCI config

- CONTRIBUTING.md
- codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/LongOerSerializerTest.java
- ildcp-core/src/test/java/org/interledger/ildcp/IldcpResponsePacketHandlerTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressPrefixTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
> Code cleanups and improves codacy code quality

- README.md
The following commit hashes are missing their DCO sign-off, but I attest these commits were made by me.
- a1bc1540f5725a97117121e34c91a80f6edcd5ed
Signed-off-by: Adrian Hope-Bailie adrian@hopebailie.com
> DCO Attestation for prior commits

- btp-core/src/main/java/org/interledger/btp/BtpSession.java
- codecs-parent/codecs-btp/src/test/java/org/interledger/codecs/btp/AsnBtpInstantBadValuesDecodingTest.java
- codecs-parent/codecs-btp/src/test/java/org/interledger/codecs/btp/AsnBtpInstantSerializationBytesTest.java
- codecs-parent/codecs-btp/src/test/java/org/interledger/codecs/btp/AsnBtpInstantSerializationTest.java
- stream-parent/stream-core/src/main/java/org/interledger/stream/StreamConnectionClosedException.java
> Addresses code quality issues in btp related modules and LGTM alerts

- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerDeserializers.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerSerializers.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/addressprefix/InterledgerAddressPrefixDeserializer.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/addressprefix/InterledgerAddressPrefixModule.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/addressprefix/InterledgerAddressPrefixSerializer.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/InterledgerModuleTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/addressprefix/InterledgerAddressPrefixModuleTest.java
> add module/serializer/deserializer for address prefix #371

- codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecULTest.java
- codecs-parent/codecs-ilp/src/test/java/org/interledger/codecs/ilp/InterledgerPreparePacketOerSerializerTests.java
- codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/StreamPacketFixturesTest.java
- ildcp-core/src/test/java/org/interledger/ildcp/IldcpRequestTest.java
- ildcp-core/src/test/java/org/interledger/ildcp/IldcpResponsePacketTest.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/addressprefix/InterledgerAddressPrefixDeserializer.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdDeserializerTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdSerializerTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeIdDeserializerTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeSerializerTest.java
- link-parent/link-core/src/test/java/org/interledger/link/LinkTest.java
- link-parent/link-core/src/test/java/org/interledger/link/LoopbackLinkTest.java
- link-parent/link-core/src/test/java/org/interledger/link/PacketRejectorTest.java
- link-parent/link-core/src/test/java/org/interledger/link/PingLoopbackLinkTest.java
- pom.xml
- stream-parent/stream-core/src/test/java/org/interledger/stream/StreamPacketTest.java
> Fixes #369 Updates checkstyle and fixes warnings breaking build

- examples-parent/send-money/README.md
- examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java
- link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLink.java
- link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLinkFactory.java
- link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLinkSettings.java
- link-parent/link-ilp-over-http/src/test/java/org/interledger/link/http/IlpOverHttpLinkSettingsTest.java
- link-parent/link-ilp-over-http/src/test/java/org/interledger/link/http/IlpOverHttpLinkTest.java
> make incoming and outgoing link settings optional #373

- stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StatelessStreamReceiver.java
- stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/StatelessStreamReceiverTest.java
> expand decoding exception #378

- spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/SimpleSpspClient.java
- spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/rust/InterledgerRustNodeClient.java
- spsp-parent/spsp-client/src/test/java/org/interledger/spsp/client/SimpleSpspClientTest.java
- spsp-parent/spsp-core/pom.xml
- spsp-parent/spsp-core/src/main/java/org/interledger/spsp/PaymentPointerResolver.java
- spsp-parent/spsp-core/src/test/java/org/interledger/spsp/PaymentPointerResolverTest.java
- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SimpleStreamSenderIT.java
> Fixes rust auth handler for ILP-over-HTTP

- link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpConstants.java
- link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLink.java
This fix is for issue #386
Removed an extra space from variable BEARER in IlpOverHttpConstants file.
Added a variable called BEARER_WITH_SPACE in IlpOverHttpLink file.
> Code Change

- ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java
- ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
> Stop interning InterledgerAddresses

- checkstyle.xml
- pom.xml
> Update Checkstyle to 8.29

- .circleci/config.yml
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerDeserializers.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/InterledgerSerializers.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdDeserializer.java
- jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeDeserializer.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/InterledgerModuleTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/spsp/SharedSecretDeserializerTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/spsp/SharedSecretModuleTest.java
- jackson-datatypes/src/test/java/org/interledger/quilt/jackson/spsp/SharedSecretSerializerTest.java
* Add other Interledger types to InterledgerModule
* Improve unit tests.
> Misc cleanup

- spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/SimpleSpspClient.java
- spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/SpspClient.java
- spsp-parent/spsp-client/src/test/java/org/interledger/spsp/client/SimpleSpspClientTest.java
Minor changes to improve SPSP content-negotiation, especially for outside software like the Connector.
> Cleanup SPSP Headers

- stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
> Fix flaky unit test.

- link-parent/link-core/src/main/java/org/interledger/link/LoopbackLink.java
- link-parent/link-core/src/main/java/org/interledger/link/PingLoopbackLink.java
- link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLink.java
- link-parent/link-stateless-spsp-receiver/src/main/java/org/interledger/link/spsp/StatelessSpspReceiverLink.java
- stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java
- stream-parent/stream-core/src/main/java/org/interledger/stream/crypto/AesGcmStreamEncryptionService.java
> Improve logging output.

- .circleci/config.yml
- examples-parent/send-money/README.md
- examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java
> fixes README for ripplex
